name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          install_components: 'gke-gcloud-auth-plugin'
          export_default_credentials: true

      - name: build and push the docker image
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        run: |
          gcloud auth configure-docker europe-west9-docker.pkg.dev
          docker build -t europe-west9-docker.pkg.dev/$GOOGLE_PROJECT/reverse-ip/reverse-ip-app:latest .
          docker push europe-west9-docker.pkg.dev/$GOOGLE_PROJECT/reverse-ip/reverse-ip-app:latest

      - name: deploy to GKE
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        run: |
          gcloud container clusters get-credentials autopilot-cluster-1 --region europe-west9
          helm upgrade --install --recreate-pods reverse-ip-app --namespace reverse-ip-app --create-namespace ./helm